name: Clans
version: ${project.version}
authors: [ Hempfest, ms5984 ]
api-version: 1.13
depend: [ Labyrinth ]
softdepend: [ Enterprise, Vault ]
loadbefore: [ DiscordSRV, Guppy ]
description: ${project.description}
website: ${project.url}/wiki
main: com.github.sanctum.clans.ClansJavaPlugin
