name: ClansPro
version: 1.3.7
authors: [ Hempfest, ms5984 ]
api-version: 1.13
depend: [ Labyrinth ]
softdepend: [ Enterprise, Vault ]
loadbefore: [ DiscordSRV ]
description: A premium & unique alternative to Factions.
website: https://github.com/the-h-team/ClansPro/wiki
main: com.github.sanctum.clans.ClansJavaPlugin